global:
  # "LoadBalancer" or "NodePort"
  ServiceType: NodePort
  # Set the NameSpace field to desired Kubernetes namespace. Defaults to 'default' namespace
  NameSpace: default
  scm:
    # "gitlab" or "bitbucket"
    type: "gitlab"
  registry:
    # "artifactory" or "docker-registry"
    type: "artifactory"
  version: 1.2
  persistence:
    ontap:
      # ontap data lif IP address
      dataIP: ""
